---
- name: Remove files downloaded to /tmp
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/amazon-cloudwatch-agent.gpg
    - /tmp/{{ cwa_pkg_file }}
    - /tmp/{{ cwa_sig_file }}
