---
dependencies: []

galaxy_info:
  author: newtonne
  role_name: cloudwatchagent
  description: Installs and configures the Amazon Unified CloudWatch Agent

  license: MIT

  min_ansible_version: 2.4

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal

  galaxy_tags:
    - monitoring
    - cloudwatch
    - aws
    - cloud
    - system
